version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "200970:200970"
    container_name: frontend_service
    working_dir: 200970_frontend

  auth:
    build:
      context: ./Auth
      dockerfile: Dockerfile
    ports:
      - "600970:600970"
    container_name: auth_service

  classrooms:
    build:
      context: ./Classrooms
      dockerfile: Dockerfile
    ports:
      - "500970:500970"
    container_name: classrooms_service

  event-bus:
    build:
      context: ./event-bus
      dockerfile: Dockerfile
    ports:
      - "400970:400970"
    container_name: event_bus_service

  post:
    build:
      context: ./Post
      dockerfile: Dockerfile
    ports:
      - "300970:300970"
    container_name: post_service

  mongo:
    image: mongo:latest
    container_name: mongodb_service
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
